export const dataMocked = [
  {
    firstName: 'Sophia',
    lastName: 'Johnson',
    dateOfBirthFormat: '5 mars 1989',
    departement: 'Sales',
    street: '123 Main Street',
    city: 'San Francisco',
    state: 'Alabama',
    zipCode: '94105',
    startDateFormat: '1 janvier 2023',
  },
  {
    firstName: 'Ethan',
    lastName: 'Martinez',
    dateOfBirthFormat: '12 juillet 1995',
    departement: 'Marketing',
    street: '456 Elm Street',
    city: 'New York',
    state: 'Alaska',
    zipCode: '10001',
    startDateFormat: '15 mars 2022',
  },
  {
    firstName: 'Isabella',
    lastName: 'Brown',
    dateOfBirthFormat: '18 septembre 1987',
    departement: 'Engineering',
    street: '789 Oak Avenue',
    city: 'Los Angeles',
    state: 'Arizona',
    zipCode: '90001',
    startDateFormat: '10 février 2024',
  },
  {
    firstName: 'Mason',
    lastName: 'Lee',
    dateOfBirthFormat: '9 avril 1990',
    departement: 'Human Resources',
    street: '1011 Pine Road',
    city: 'Chicago',
    state: 'Arkansas',
    zipCode: '60601',
    startDateFormat: '20 mai 2023',
  },
  {
    firstName: 'Ava',
    lastName: 'Garcia',
    dateOfBirthFormat: '23 mai 1993',
    departement: 'Legal',
    street: '1213 Cedar Lane',
    city: 'Houston',
    state: 'California',
    zipCode: '77001',
    startDateFormat: '5 avril 2022',
  },
  {
    firstName: 'Noah',
    lastName: 'Rodriguez',
    dateOfBirthFormat: '30 décembre 1984',
    departement: 'Sales',
    street: '1415 Maple Street',
    city: 'Miami',
    state: 'Alabama',
    zipCode: '33101',
    startDateFormat: '3 juin 2022',
  },
  {
    firstName: 'Olivia',
    lastName: 'Hernandez',
    dateOfBirthFormat: '8 novembre 1998',
    departement: 'Marketing',
    street: '1617 Walnut Avenue',
    city: 'Phoenix',
    state: 'Alaska',
    zipCode: '85001',
    startDateFormat: '7 septembre 2023',
  },
  {
    firstName: 'William',
    lastName: 'Lopez',
    dateOfBirthFormat: '14 février 1980',
    departement: 'Engineering',
    street: '1819 Birch Road',
    city: 'Philadelphia',
    state: 'Arizona',
    zipCode: '19019',
    startDateFormat: '12 décembre 2022',
  },
  {
    firstName: 'Emily',
    lastName: 'Gonzalez',
    dateOfBirthFormat: '20 juin 1986',
    departement: 'Human Resources',
    street: '2021 Pine Avenue',
    city: 'San Antonio',
    state: 'Arkansas',
    zipCode: '78201',
    startDateFormat: '2 novembre 2022',
  },
  {
    firstName: 'James',
    lastName: 'Perez',
    dateOfBirthFormat: '17 août 1992',
    departement: 'Sales',
    street: '2223 Oak Street',
    city: 'San Diego',
    state: 'California',
    zipCode: '92101',
    startDateFormat: '14 janvier 2024',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Williams',
    dateOfBirthFormat: '3 janvier 1996',
    departement: 'Marketing',
    street: '2425 Maple Lane',
    city: 'Dallas',
    state: 'Alabama',
    zipCode: '75201',
    startDateFormat: '18 juillet 2022',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Jackson',
    dateOfBirthFormat: '11 avril 1994',
    departement: 'Human Resources',
    street: '2627 Cedar Road',
    city: 'San Jose',
    state: 'Alaska',
    zipCode: '95101',
    startDateFormat: '20 septembre 2023',
  },
  {
    firstName: 'Amelia',
    lastName: 'Anderson',
    dateOfBirthFormat: '27 février 1983',
    departement: 'Legal',
    street: '2829 Elm Avenue',
    city: 'Austin',
    state: 'Arizona',
    zipCode: '73301',
    startDateFormat: '8 août 2022',
  },
  {
    firstName: 'Michael',
    lastName: 'Thomas',
    dateOfBirthFormat: '25 mai 1985',
    departement: 'Sales',
    street: '3031 Pine Lane',
    city: 'Jacksonville',
    state: 'Arkansas',
    zipCode: '32201',
    startDateFormat: '16 avril 2023',
  },
  {
    firstName: 'Elizabeth',
    lastName: 'White',
    dateOfBirthFormat: '10 septembre 1990',
    departement: 'Marketing',
    street: '3233 Oak Road',
    city: 'Indianapolis',
    state: 'California',
    zipCode: '46201',
    startDateFormat: '29 novembre 2022',
  },
  {
    firstName: 'Alexander',
    lastName: 'Harris',
    dateOfBirthFormat: '19 décembre 1987',
    departement: 'Engineering',
    street: '3435 Cedar Lane',
    city: 'San Francisco',
    state: 'Alabama',
    zipCode: '94105',
    startDateFormat: '4 janvier 2024',
  },
  {
    firstName: 'Sofia',
    lastName: 'Clark',
    dateOfBirthFormat: '16 juillet 1981',
    departement: 'Human Resources',
    street: '3637 Elm Street',
    city: 'Columbus',
    state: 'Alaska',
    zipCode: '43201',
    startDateFormat: '19 octobre 2022',
  },
  {
    firstName: 'Daniel',
    lastName: 'Lewis',
    dateOfBirthFormat: '21 août 1984',
    departement: 'Legal',
    street: '3839 Pine Avenue',
    city: 'Charlotte',
    state: 'Arizona',
    zipCode: '28201',
    startDateFormat: '22 septembre 2023',
  },
  {
    firstName: 'Mia',
    lastName: 'Walker',
    dateOfBirthFormat: '7 novembre 1986',
    departement: 'Sales',
    street: '4041 Maple Road',
    city: 'Seattle',
    state: 'Arkansas',
    zipCode: '98101',
    startDateFormat: '11 mai 2022',
  },
  {
    firstName: 'David',
    lastName: 'Young',
    dateOfBirthFormat: '26 janvier 1982',
    departement: 'Marketing',
    street: '4243 Oak Lane',
    city: 'Denver',
    state: 'California',
    zipCode: '80201',
    startDateFormat: '25 décembre 2023',
  },
  {
    firstName: 'Liam',
    lastName: 'Smith',
    dateOfBirthFormat: '14 avril 1993',
    departement: 'Sales',
    street: '123 Oak Street',
    city: 'Portland',
    state: 'Alabama',
    zipCode: '97201',
    startDateFormat: '10 février 2023',
  },
  {
    firstName: 'Emma',
    lastName: 'Turner',
    dateOfBirthFormat: '19 mai 1990',
    departement: 'Marketing',
    street: '456 Elm Avenue',
    city: 'Boston',
    state: 'Alaska',
    zipCode: '02101',
    startDateFormat: '15 mars 2022',
  },
  {
    firstName: 'Luna',
    lastName: 'Harris',
    dateOfBirthFormat: '23 août 1986',
    departement: 'Engineering',
    street: '789 Pine Lane',
    city: 'Atlanta',
    state: 'Arizona',
    zipCode: '30301',
    startDateFormat: '5 avril 2024',
  },
  {
    firstName: 'Noah',
    lastName: 'Cook',
    dateOfBirthFormat: '30 novembre 1985',
    departement: 'Human Resources',
    street: '1011 Cedar Road',
    city: 'Detroit',
    state: 'Arkansas',
    zipCode: '48201',
    startDateFormat: '20 mai 2023',
  },
  {
    firstName: 'Olivia',
    lastName: 'Ward',
    dateOfBirthFormat: '5 février 1989',
    departement: 'Legal',
    street: '1213 Oak Avenue',
    city: 'Minneapolis',
    state: 'California',
    zipCode: '55401',
    startDateFormat: '1 avril 2022',
  },
  {
    firstName: 'William',
    lastName: 'Baker',
    dateOfBirthFormat: '10 mars 1991',
    departement: 'Sales',
    street: '1415 Pine Road',
    city: 'Orlando',
    state: 'Alabama',
    zipCode: '32801',
    startDateFormat: '3 juin 2022',
  },
  {
    firstName: 'Ava',
    lastName: 'Russell',
    dateOfBirthFormat: '15 septembre 1997',
    departement: 'Marketing',
    street: '1617 Cedar Street',
    city: 'Tampa',
    state: 'Alaska',
    zipCode: '33601',
    startDateFormat: '7 septembre 2023',
  },
  {
    firstName: 'James',
    lastName: 'Griffin',
    dateOfBirthFormat: '20 octobre 1980',
    departement: 'Engineering',
    street: '1819 Pine Avenue',
    city: 'Nashville',
    state: 'Arizona',
    zipCode: '37201',
    startDateFormat: '12 décembre 2022',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Diaz',
    dateOfBirthFormat: '25 janvier 1986',
    departement: 'Human Resources',
    street: '2021 Cedar Lane',
    city: 'Louisville',
    state: 'Arkansas',
    zipCode: '40201',
    startDateFormat: '2 novembre 2022',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Hayes',
    dateOfBirthFormat: '3 juin 1994',
    departement: 'Sales',
    street: '2223 Elm Road',
    city: 'Kansas City',
    state: 'California',
    zipCode: '64101',
    startDateFormat: '14 janvier 2024',
  },
  {
    firstName: 'Amelia',
    lastName: 'Patterson',
    dateOfBirthFormat: '7 août 1983',
    departement: 'Marketing',
    street: '2425 Pine Street',
    city: 'Milwaukee',
    state: 'Alabama',
    zipCode: '53201',
    startDateFormat: '18 juillet 2022',
  },
  {
    firstName: 'Michael',
    lastName: 'Flores',
    dateOfBirthFormat: '12 décembre 1990',
    departement: 'Human Resources',
    street: '2627 Cedar Avenue',
    city: 'Las Vegas',
    state: 'Alaska',
    zipCode: '89101',
    startDateFormat: '20 septembre 2023',
  },
  {
    firstName: 'Sophia',
    lastName: 'Simmons',
    dateOfBirthFormat: '17 avril 1985',
    departement: 'Legal',
    street: '2829 Elm Lane',
    city: 'Albuquerque',
    state: 'Arizona',
    zipCode: '87101',
    startDateFormat: '8 août 2022',
  },
  {
    firstName: 'Alexander',
    lastName: 'Foster',
    dateOfBirthFormat: '21 juillet 1981',
    departement: 'Sales',
    street: '3031 Pine Road',
    city: 'Honolulu',
    state: 'Arkansas',
    zipCode: '96801',
    startDateFormat: '16 avril 2023',
  },
  {
    firstName: 'Mia',
    lastName: 'Gonzalez',
    dateOfBirthFormat: '26 novembre 1987',
    departement: 'Marketing',
    street: '3233 Cedar Street',
    city: 'Anchorage',
    state: 'California',
    zipCode: '99501',
    startDateFormat: '29 novembre 2022',
  },
  {
    firstName: 'William',
    lastName: 'Carter',
    dateOfBirthFormat: '1 mars 1984',
    departement: 'Engineering',
    street: '3435 Pine Avenue',
    city: 'Raleigh',
    state: 'Alabama',
    zipCode: '27601',
    startDateFormat: '4 janvier 2024',
  },
  {
    firstName: 'Ella',
    lastName: 'Hill',
    dateOfBirthFormat: '15 août 1981',
    departement: 'Human Resources',
    street: '3637 Cedar Lane',
    city: 'Richmond',
    state: 'Alaska',
    zipCode: '23201',
    startDateFormat: '19 octobre 2022',
  },
  {
    firstName: 'James',
    lastName: 'Wright',
    dateOfBirthFormat: '19 novembre 1984',
    departement: 'Sales',
    street: '3839 Elm Road',
    city: 'Salt Lake City',
    state: 'Arizona',
    zipCode: '84101',
    startDateFormat: '22 septembre 2023',
  },
  {
    firstName: 'Ava',
    lastName: 'Edwards',
    dateOfBirthFormat: '24 janvier 1987',
    departement: 'Marketing',
    street: '4041 Pine Street',
    city: 'Santa Fe',
    state: 'Arkansas',
    zipCode: '87501',
    startDateFormat: '11 mai 2022',
  },
  {
    firstName: 'Liam',
    lastName: 'Collins',
    dateOfBirthFormat: '3 avril 1982',
    departement: 'Engineering',
    street: '4243 Cedar Avenue',
    city: 'Boise',
    state: 'California',
    zipCode: '83701',
    startDateFormat: '25 décembre 2023',
  },
]
